add prepare step to remove ".cargo/config"
rust-lang/rustwide pull request #22
Opened 2020-05-06 12:42 UTC by Freax13

fixes: https://github.com/rust-lang/docs.rs/issues/650

2020-05-06 17:15 UTC, emilyalbini requested changes
Thanks for this PR! Other than addressing the comment below, could you add a changelog entry (in a new "Changed" subsection under "Unreleased") for this?

2020-05-06 17:15 UTC, pietroalbini commented on src/prepare.rs
> +            remove_file(path)?;
Can you add an `info!` here that says the `.cargo/config` file was deleted? I'd prefer for all the changes done during the prepare to be logged, so it's easy to see what changed between the local build and the docs.rs build when debugging build differences.

2020-05-07 17:14 UTC, emilyalbini approved these changes

2020-05-07 17:14 UTC, merged

2020-05-07 17:15 UTC, pietroalbini commented
Thanks for the PR! I'll release a new rustwide version after merging https://github.com/rust-lang/rustwide/pull/20.

2020-05-07 17:44 UTC, pietroalbini commented
Released rustwide 0.7.0! Note that there are breaking changes in it (see the changelog).

2020-05-20 07:31 UTC, phil-opp commented
> Released rustwide 0.7.0! Note that there are breaking changes in it (see the changelog).

I think you forgot to add the "0.7.0" heading to the changelog. It still shows the 0.7.0 changes under "unreleased".