Support custom registries
rust-lang/rustwide pull request #48
Opened 2020-10-16 18:50 UTC by l4l

Required for docs.rs with custom index location as stated in [this comment](https://github.com/rust-lang/docs.rs/issues/767#issuecomment-710296929).

2020-10-19 08:36 UTC, pietroalbini requested changes
Thanks for the PR! I left some inline comments, and there are some more general changes to make:

* For all items that are not part of the public API, could you switch the visibility from `pub` to `pub(super)`? That way it's clear those are not available publicly, and we're guaranteed to get unused item warnings.
* It'd be nice to add a buildtest that fetches a crate from an alternative registry. One you can use is the [`foo` crate on `staging.crates.io`](https://staging.crates.io/crates/foo) ([index url](https://github.com/rust-lang/staging.crates.io-index)), crates.io's staging instance.
* Could you add a changelog item?

2020-10-19 08:36 UTC, pietroalbini commented on src/crates/registry.rs
> +        )
What we did in other parts of rustwide is using the `percent_encoding` crate to urlencode the paths. [See an example in the git repos support.](https://github.com/rust-lang/rustwide/blob/d2c0723c88a7b05715b4942226acebf54d0b6328/src/crates/git.rs#L53-L58) What I'd do is move the definition of `ENCODE_SET` out of that module and into `crate::utils`, and use the same mechanism here.

2020-10-19 08:36 UTC, pietroalbini commented on src/crates/registry.rs
> +            Registry::Alternative(_alt) => todo!(),
Can we replace this with the index URL?

2020-10-19 08:36 UTC, pietroalbini commented on src/crates/registry.rs
> +            Registry::Alternative(alt) => format!("{}-sources", alt.index()),
This should probably use the encoded path (from `alt.index_folder()`).

2020-10-19 08:36 UTC, pietroalbini commented on src/crates/registry.rs
> +            Registry::CratesIo => "cratesios-sources".into(),
Let's maintain compatibility with the existing directories.

```suggestion
            Registry::CratesIo => "cratesio-sources".into(),
```

2020-10-19 08:36 UTC, pietroalbini commented on src/crates/registry.rs
> +impl RegistryCrate {
Could you move the impl below the struct definition?

2020-10-19 08:36 UTC, pietroalbini commented on src/crates/mod.rs
> +    CratesIO(registry::RegistryCrate),
Maybe let's rename the varianto to `Registry`?

2020-10-20 08:52 UTC, pietroalbini reviewed
This looks better! Once a buildtest that fetches from staging.crates.io is added this is ready to land!

2020-10-20 08:52 UTC, pietroalbini commented on src/crates/mod.rs
> +    /// Load a create from specified registry.
```suggestion
    /// Load a crate from specified registry.
```

2020-10-20 09:11 UTC, l4l commented
Oh, thanks for noticing missed that commit at local rebase. Fortunately git remembers it

2020-10-20 09:36 UTC, pietroalbini approved these changes

2020-10-20 09:36 UTC, merged

2020-10-20 09:36 UTC, pietroalbini commented
Thank you so much for this PR!